---
services:
  - service:
    name: User
    description: Auth and user list manipulating service
    host: localhost
    port: 1000
    id: 0
    db_user: eduflow_users
    db: eduflow_users
db:
  host: localhost
  port: 5432
